import { useState } from "react";
import { Chrome, Mic2 } from "lucide-react";
import { registerWithEmail } from "../../services/auth";
import { useAuth } from "../../context/AuthContext";
export function AuthPage() {
    const { signIn, googleSignIn } = useAuth(); const [mode, setMode] = useState<"signin" | "signup">("signin"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [pw, setPw] = useState(""); const [busy, setBusy] = useState(false); const [err, setErr] = useState(""); async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setErr(""); try { if (mode === "signup") await registerWithEmail(name, email, pw); else await signIn(email, pw) } catch (e) { setErr(e instanceof Error ? e.message : "Authentication failed.") } finally { setBusy(false) } } async function google() { setBusy(true); setErr(""); try { await googleSignIn() } catch (e) { setErr(e instanceof Error ? e.message : "Google sign in failed.") } finally { setBusy(false) } } return <div className="auth-layout"><section className="auth-visual"><div className="aria-orb large"><Mic2 size={54} /></div><span className="eyebrow">FitMind Rx presents</span><h1>ARIA</h1><p className="tagline">
        <span className="aria-letter a">A</span>udio{" "}
        <span className="aria-letter r">R</span>ep{" "}
        <span className="aria-letter i">I</span>ntelligence{" "}
        <span className="aria-letter a2">A</span>dvisor
    </p><p className="hero-muted">Your voice coach anywhere.</p></section><section className="auth-card"><span className="eyebrow">FitMind Rx</span><h2>{mode === "signin" ? "Welcome back." : "Start your ARIA account."}</h2><p className="muted">Simple access. Your trainer lives in your headphones.</p><form onSubmit={submit} className="stack">{mode === "signup" && <label>Full name<input value={name} onChange={e => setName(e.target.value)} required /></label>}<label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" minLength={6} value={pw} onChange={e => setPw(e.target.value)} required /></label>{err && <div className="error-box">{err}</div>}<button className="primary-button" disabled={busy}>{busy ? "Please wait…" : mode === "signin" ? "Sign in" : "Create account"}</button></form><div className="divider"><span>or</span></div><button className="secondary-button" onClick={() => void google()} disabled={busy}><Chrome size={17} /> Continue with Google</button><button className="text-button" onClick={() => setMode(mode === "signin" ? "signup" : "signin")}>{mode === "signin" ? "Create a new account" : "Already have an account? Sign in"}</button>{mode === "signup" && <div className="notice">New accounts are created as <strong>pending</strong> until an administrator approves them.</div>}<div style={{ marginTop: "32px", fontSize: "11px", color: "#6f7b8c", textAlign: "center" }}>Ejercicios provistos por <a href="https://gymvisual.com/" target="_blank" rel="noopener noreferrer" style={{ color: "#7cf7d4", textDecoration: "none" }}>Gym Visual</a></div></section></div>
}
